# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6cff883b763a942adb575f20b608346d78cbfb03c9f478e529c8a68e580519f2743cf8a0b5b0122338112218432540eb9f8d0e71d89b8f551c2d5ff42eff3ef8

test:
  secret_key_base: d6d28a04b3abc1329eb70122d7e9b34dd87f6023e637e1fe739c1d43849c5863486393d33c77fdfade24cc8f585f37b9f369eed611cc7f35b0e12760b03a0fc2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
